### ISSUE TITLE
possible memory leak in the future if we switch to a multithreaded ztpd

### ISSUE THREAD

**Issue by forwardpointer** [microsoft/wifi-ztp#25]
I noticed that if ztpd_run() returns a negative error code then nothing will be deinitialized before the main() function exits. Currently ztpd is all single-threaded, so this isn't an issue, as when the process exits all memory the process used will be released by the kernel. However, if in the future someone decides to add multi-threaded or multi-process capabilities to ztpd this will result in a possible memory leak. I thought I'd make note of this here just in case that happens.

**Comment by abeltrano** [comment]
Good find. It looks like the fix should be pretty easy: remove the return statement and perhaps cache the `ztpd_run()` return value to be returned from `main()`.
